add compliance score system test
kubescape/workflows pull request #25
Opened 2023-05-10 07:48 UTC by YiscahLevySilas1

2023-05-10 07:59 UTC, yuleib requested changes

2023-05-10 07:59 UTC, yuleib commented on .github/workflows/kubescape-cli-e2e-tests.yaml
> +                    scan_compliance_score
```suggestion
                    "scan_compliance_score"
```

2023-05-14 08:47 UTC, yuleib approved these changes

2023-05-14 12:27 UTC, dwertent approved these changes

2023-05-14 12:27 UTC, merged